<?php

return [

    /*
    |--------------------------------------------------------------------------
    | Custom messages
    |--------------------------------------------------------------------------
    |
    | The following language lines contain the default error messages used by
    | the validator class. Some of these rules have multiple versions such
    | as the size rules. Feel free to tweak each of these messages here.
    |
    */

    '10000' => [
        'code' => '10000',
        'message' => 'Not processed',
    ],

    '10001' => [
        'code' => '10001',
        'message' => 'Active',
    ],
    '10002' => [
        'code' => '10002',
        'message' => 'Inactive',
    ],
    '10003' => [
        'code' => '10003',
        'message' => 'Duplicate sale reference number',
    ],
    '10004' => [
        'code' => '10004',
        'message' => 'Duplicate defect item reference number',
    ],
    '10005' => [
        'code' => '10005',
        'message' => 'SP retail key file or pass phrase not Found',
    ],
    '10006' => [
        'code' => '10006',
        'message' => 'Client retail key file or pass phrase not found',
    ],
    '10007' => [
        'code' => '10007',
        'message' => 'Successful',
    ],
    '10008' => [
        'code' => '10008',
        'message' => 'Failed to publish messages',
    ],
    '10009' => [
        'code' => '10009',
        'message' => 'Signature verification failed',
    ],
    '10010' => [
        'code' => '10010',
        'message' => 'Invalid data request',
    ],
    '10011' => [
        'code' => '10011',
        'message' => 'Failure to process request at this time',
    ],
    '10012' => [
        'code' => '10012',
        'message' => 'Missing header api version ',
    ],
    '10013' => [
        'code' => '10013',
        'message' => 'Missing header request Id ',
    ],
    '10014' => [
        'code' => '10014',
        'message' => 'Missing header response Id',
    ],
    '10015' => [
        'code' => '10015',
        'message' => 'Successful received by external system',
    ],
    '10016' => [
        'code' => '10016',
        'message' => 'Processed successful by external system',
    ],
    '10017' => [
        'code' => '10017',
        'message' => 'Data not found',
    ],
    '10018' => [
        'code' => '10018',
        'message' => 'Method not allowed',
    ],
    '10019' => [
        'code' => '10019',
        'message' => 'Missing header system Id',
    ],
    '10020' => [
        'code' => '10020',
        'message' => 'Missing header device Id',
    ],
    '10021' => [
        'code' => '10021',
        'message' => 'Missing header sp reference number',
    ],
    '10022' => [
        'code' => '10022',
        'message' => 'Missing header generated by',
    ],
    '10023' => [
        'code' => '10023',
        'message' => 'Missing header generated date',
    ],
    '10024' => [
        'code' => '10024',
        'message' => 'Missing header status code',
    ],
    '10025' => [
        'code' => '10025',
        'message' => 'Unauthorized request',
    ],
    '10026' => [
        'code' => '10026',
        'message' => 'Invalid username or password',
    ],
    '10027' => [
        'code' => '10027',
        'message' => 'User account is disabled',
    ],
    '10028' => [
        'code' => '10028',
        'message' => 'User account is locked',
    ],
    '10029' => [
        'code' => '10029',
        'message' => 'User account is expired',
    ],
    '10030' => [
        'code' => '10030',
        'message' => 'User credential is expired',
    ],
    '10031' => [
        'code' => '10031',
        'message' => 'Invalid base64 string',
    ],
    '10032' => [
        'code' => '10032',
        'message' => 'Invalid access token',
    ],
    '10033' => [
        'code' => '10033',
        'message' => 'Role name provided mismatch',
    ],
    '10034' => [
        'code' => '10034',
        'message' => 'Missing header username',
    ],
    '10035' => [
        'code' => '10035',
        'message' => 'Missing header permission name',
    ],
    '10036' => [
        'code' => '10036',
        'message' => 'Missing header role name',
    ],
    '10037' => [
        'code' => '10037',
        'message' => 'Missing header access token',
    ],
    '10038' => [
        'code' => '10038',
        'message' => 'User account is online',
    ],
    '10039' => [
        'code' => '10039',
        'message' => 'Missing search criteria',
    ],
    '10040' => [
        'code' => '10040',
        'message' => 'Invalid systemId configuration',
    ]
    ,
    '10041' => [
        'code' => '10041',
        'message' => 'Inactive systemId',
    ],
    '10042' => [
        'code' => '10042',
        'message' => 'Missing header setup type',
    ],
    '10043' => [
        'code' => '10043',
        'message' => 'Setup type contains transaction not allowed to update its details',
    ],
    '10044' => [
        'code' => '10044',
        'message' => 'Invalid or inactive region',
    ],
    '10045' => [
        'code' => '10045',
        'message' => 'Invalid or inactive Service Provider',
    ],
    '10046' => [
        'code' => '10046',
        'message' => 'Invalid or inactive district',
    ],
    '10047' => [
        'code' => '10047',
        'message' => 'Invalid or inactive  Sub Service Provider',
    ],
    '10048' => [
        'code' => '10048',
        'message' => 'Invalid or inactive retailCenter',
    ],
    '10049' => [
        'code' => '10049',
        'message' => 'Invalid or inactive currency',
    ],
    '10050' => [
        'code' => '10050',
        'message' => 'Invalid or inactive device model',
    ],
    '10051' => [
        'code' => '10051',
        'message' => 'Invalid or inactive device Id',
    ],
    '10052' => [
        'code' => '10052',
        'message' => 'Invalid or inactive role category',
    ],
    '10053' => [
        'code' => '10053',
        'message' => 'Invalid or inactive username',
    ],
    '10054' => [
        'code' => '10054',
        'message' => 'Invalid or inactive identity Type',
    ],
    '10055' => [
        'code' => '10055',
        'message' => 'Invalid or inactive exchange rate',
    ],
    '10056' => [
        'code' => '10056',
        'message' => 'Item name already exists',
    ],
    '10057' => [
        'code' => '10057',
        'message' => 'Package already exists',
    ],
    '10058' => [
        'code' => '10058',
        'message' => 'Invalid or inactive device',
    ],
    '10059' => [
        'code' => '10059',
        'message' => 'Device Id already exists',
    ],
    '10060' => [
        'code' => '10060',
        'message' => 'Transaction still waiting for the final response',
    ],
    '10061' => [
        'code' => '10061',
        'message' => 'Invalid or inactive both TIN and serial number',
    ],
    '10062' => [
        'code' => '10062',
        'message' => 'Serial number provided already exists to other taxpayer',
    ],

    '10063' => [
        'code' => '10001',
        'message' => 'Bulk transaction currently not supported',
    ],
    '10064' => [
        'code' => '10064',
        'message' => 'Sale items not found',
    ],
    '10065' => [
        'code' => '10065',
        'message' => 'Invalid or inactive Efdms registration',
    ],
    '10066' => [
        'code' => '10066',
        'message' => 'Exchange rate amount mismatches',
    ],
    '10067' => [
        'code' => '10067',
        'message' => 'Invalid or inactive payment type',
    ],
    '10068' => [
        'code' => '10068',
        'message' => 'Wrong bill equivalent amount',
    ],
    '10069' => [
        'code' => '10069',
        'message' => 'Wrong sale equivalent amount',
    ],
    '10070' => [
        'code' => '10070',
        'message' => 'Wrong sale tax equivalent amount',
    ],
    '10071' => [
        'code' => '10071',
        'message' => 'Wrong sale discount equivalent amount',
    ],
    '10072' => [
        'code' => '10072',
        'message' => 'Wrong sale cost equivalent amount',
    ],
    '10073' => [
        'code' => '10073',
        'message' => 'Wrong sale profit equivalent amount',
    ],
    '10074' => [
        'code' => '10074',
        'message' => 'Total item billed amount mismatches the billed amount',
    ],
    '10075' => [
        'code' => '10075',
        'message' => 'Total item billed equivalent amount mismatches the billed equivalent amount',
    ],
    '10076' => [
        'code' => '10076',
        'message' => 'Total sale item amount mismatches the sale amount',
    ],
    '10077' => [
        'code' => '10077',
        'message' => 'Total sale item equivalent amount mismatches the sale equivalent amount',
    ],
    '10078' => [
        'code' => '10078',
        'message' => 'Total sale item tax amount mismatches the sale tax amount',
    ],
    '10079' => [
        'code' => '10079',
        'message' => 'Total sale item tax equivalent amount mismatches the sale tax equivalent amount',
    ],
    '10080' => [
        'code' => '10080',
        'message' => 'Total sale item discount amount mismatches the sale discount amount',
    ],
    '10081' => [
        'code' => '10081',
        'message' => 'Total sale item discount equivalent amount mismatches the sale discount equivalent amount',
    ],
    '10082' => [
        'code' => '10082',
        'message' => 'Total sale item cost amount mismatches the sale cost amount',
    ],
    '10083' => [
        'code' => '10083',
        'message' => 'Total sale item cost equivalent amount mismatches the sale cost equivalent amount',
    ],
    '10084' => [
        'code' => '10084',
        'message' => 'Total sale item profit amount mismatches the sale profit amount',
    ],
    '10085' => [
        'code' => '10085',
        'message' => 'Total sale item profit equivalent amount mismatches the sale profit equivalent amount',
    ],
    '10086' => [
        'code' => '10086',
        'message' => 'Wrong item billed equivalent amount',
    ],
    '10087' => [
        'code' => '10087',
        'message' => 'Wrong sale item equivalent amount',
    ],
    '10088' => [
        'code' => '10088',
        'message' => 'Wrong sale item tax equivalent amount',
    ],
    '10089' => [
        'code' => '10089',
        'message' => 'Wrong sale item discount equivalent amount',
    ],
    '10090' => [
        'code' => '10090',
        'message' => 'Wrong sale item cost equivalent amount',
    ],
    '10091' => [
        'code' => '10091',
        'message' => 'Wrong sale item profit equivalent amount',
    ],
    '10092' => [
        'code' => '10092',
        'message' => 'Invalid or inactive item',
    ],
    '10093' => [
        'code' => '10093',
        'message' => 'Duplicate receipt verification number',
    ],
    '10094' => [
        'code' => '10094',
        'message' => 'Global counter and Daily counter and receipt number and znumber and receipt verification number mismatches',
    ],
    '10095' => [
        'code' => '10095',
        'message' => 'Invalid or inactive transaction date',
    ],
    '10096' => [
        'code' => '10096',
        'message' => 'Wrong transaction generation date',
    ],
    '10097' => [
        'code' => '10097',
        'message' => 'Invalid or inactive device number',
    ],
    '10098' => [
        'code' => '10098',
        'message' => 'Wrong purchase equivalent amount',
    ],
    '10099' => [
        'code' => '10099',
        'message' => 'Wrong purchase tax equivalent amount',
    ],
    '10100' => [
        'code' => '10100',
        'message' => 'Total item purchase amount mismatches the purchase amount',
    ],
    '10101' => [
        'code' => '10101',
        'message' => 'Total item purchase equivalent amount mismatches the purchase equivalent amount',
    ],
    '10102' => [
        'code' => '10102',
        'message' => 'Total purchase item tax amount mismatches the purchase tax amount',
    ]
    ,
    '10103' => [
        'code' => '10103',
        'message' => 'Total purchase item tax equivalent amount mismatches the purchase tax equivalent amount',
    ],
    '10104' => [
        'code' => '10104',
        'message' => 'Total purchase item quantity mismatches the purchase quantity',
    ],
    '10105' => [
        'code' => '10105',
        'message' => 'Purchase global counter and purchase daily counter and purchase reference number mismatches',
    ],
    '10106' => [
        'code' => '10106',
        'message' => 'Duplicate purchase reference number',
    ],
    '10107' => [
        'code' => '10107',
        'message' => 'Defect item quantity must be less than zero',
    ],
    '10108' => [
        'code' => '10108',
        'message' => 'Defect item global counter and defect item daily counter and defect item reference number mismatches',
    ],
    '10109' => [
        'code' => '10109',
        'message' => 'Total sale item quantity mismatches the sale quantity',
    ],
    '10110' => [
        'code' => '10110',
        'message' => 'Missing header cert serial',
    ],
    '10111' => [
        'code' => '10111',
        'message' => 'Invalid or inactive cert serial',
    ],
    '10112' => [
        'code' => '10112',
        'message' => 'Header request Id mismatches with detail request Id',
    ],
    '10113' => [
        'code' => '10113',
        'message' => 'Header version mismatches with detail version',
    ],
    '10114' => [
        'code' => '10114',
        'message' => 'Header sp reference number mismatches with detail sp reference number',
    ],
    '10115' => [
        'code' => '10115',
        'message' => 'Header system Id mismatches with detail system Id',
    ],
    '10116' => [
        'code' => '10116',
        'message' => 'Acknowledgement response Id mismatches',
    ],
    '10117' => [
        'code' => '10117',
        'message' => 'Invalid or inactive setup type',
    ],
    '10118' => [
        'code' => '10118',
        'message' => 'Header setup type mismatches with detail setup type',
    ],
    '10119' => [
        'code' => '10119',
        'message' => 'Efdms registration is blocked by TRA',
    ],
    '10120' => [
        'code' => '10120',
        'message' => 'Efdms registration is unblocked by TRA',
    ],
    '10121' => [
        'code' => '10121',
        'message' => 'Invalid or inactive device token',
    ],
    '10122' => [
        'code' => '10122',
        'message' => 'Invalid or inactive package',
    ],
    '10123' => [
        'code' => '10123',
        'message' => 'Difference in days between end date and start date is greater than 31 days',
    ],
    '10124' => [
        'code' => '10124',
        'message' => 'Wrong package paid amount',
    ],


];



